// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'eu-central-1:a1d6af8e-a60f-4a29-994d-a195b1bc98ec',
    'aws_cognito_region': 'eu-central-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'amplifydemo-hosting-mobilehub-367274425',
    'aws_content_delivery_bucket_region': 'eu-central-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2xfpx1bbpaihv.cloudfront.net',
    'aws_mobile_analytics_app_id': '1ad5075b5e4948fcb31412755a1f5256',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '8da701f2-ef27-4c8e-b463-7cb6d2a2838a',
    'aws_project_name': 'amplify-demo-2018-01-24-22-24-44',
    'aws_project_region': 'eu-central-1',
    'aws_resource_name_prefix': 'amplifydemo-mobilehub-367274425',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'eu-central-1_MtMRb86Vp',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '10chksocngldnp76k5kvjebgur',
}

export default awsmobile;
